import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingTop: -5,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F0F0F',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f4f4f4',
    marginHorizontal: 16,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 40,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
  },
  pinnedChipsRow: {
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  pinnedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginRight: 8,
  },
  pinnedChipText: {
    color: '#fff',
    fontWeight: '700',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 12,
    zIndex: 3,
    elevation: 2,
    overflow: 'visible',
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rowIcon: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    marginRight: 12,
  },
  rowIconCircle: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  rowTitle: {
    fontSize: 16,
    color: '#0F0F0F',
    fontWeight: '600',
  },
  rowSubtitle: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
  },
  leftActions: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 0,
    marginLeft: 16,
    marginRight: -25,
    height: '100%',
    zIndex: 1,
  },
  actionPill: {
    height: 60,
    width: 80,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -10,
  },
  actionPin: {
    marginRight: 0,
    width: 90,
  },
  actionEdit: {
    marginLeft: -20,
    zIndex: 1,
  },
  // right swipe (delete)
  rightActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingRight: 16,
    height: '100%',
    marginLeft: -25,
  },
  actionDelete: {
    height: 60,
    width: 90,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ef4444',
    marginTop: -10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    backgroundColor: '#ddd',
    borderRadius: 2,
    marginBottom: 8,
  },
  sheetHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sheetHeaderBtn: {
    color: '#777',
    fontWeight: '600',
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0F0F0F',
  },
  nameInput: {
    backgroundColor: '#f4f4f4',
    borderRadius: 12,
    height: 40,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  blockBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E6E6E6',
    padding: 12,
    marginBottom: 12,
  },
  blockTitle: {
    color: '#0F0F0F',
    fontWeight: '600',
    marginBottom: 10,
  },
  iconGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  iconPill: {
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#E6E6E6',
  },
  iconPillActive: {
    backgroundColor: '#2E8B57',
    borderColor: '#2E8B57',
  },
  colorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  colorDot: {
    width: 26,
    height: 26,
    borderRadius: 13,
    marginRight: 10,
    borderWidth: 2,
    borderColor: 'transparent',
  },
  colorDotActive: {
    borderColor: '#008655',
  },
  pinRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    backgroundColor: '#e5e7eb',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  checkboxChecked: {
    backgroundColor: '#2E8B57',
  },
  pinLabel: {
    color: '#0F0F0F',
    fontWeight: '600',
  },
  // sort modal rows
  sortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    marginHorizontal: 8,
    marginBottom: 10,
    backgroundColor: '#fff',
  },
  sortText: {
    color: '#0F0F0F',
  },
  radioOuter: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#cfcfcf',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#2E8B57',
  },
});

export default styles;


